import { writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { API_KEY_ENV, MODELS_URL, REQUEST_TIMEOUT_MS } from "../src/config.js";
import { parseModelCatalog } from "../src/zenmux-api.js";

// Keep this list aligned with ZenMux's recommended-model guide.
const FALLBACK_MODEL_IDS = [
  "moonshotai/kimi-k3-free",
  "moonshotai/kimi-k3",
  "openai/gpt-5.6-luna",
  "openai/gpt-5.6-terra",
  "x-ai/grok-4.5",
  "anthropic/claude-sonnet-5",
  "z-ai/glm-5.2",
  "moonshotai/kimi-k2.7-code",
  "qwen/qwen3.7-plus",
  "google/gemini-3.1-pro-preview",
  "deepseek/deepseek-v4-pro",
  "minimax/minimax-m3",
] as const;

const headers: Record<string, string> = { Accept: "application/json" };
const apiKey = process.env[API_KEY_ENV];
if (apiKey) headers.Authorization = `Bearer ${apiKey}`;

const response = await fetch(MODELS_URL, {
  headers,
  signal: AbortSignal.timeout(REQUEST_TIMEOUT_MS),
});
if (!response.ok) throw new Error(`/v1/models returned HTTP ${response.status}`);

const parsed = parseModelCatalog((await response.json()) as unknown);
if (!parsed) throw new Error("ZenMux returned an invalid model catalog");
const byId = new Map(parsed.models.map((model) => [model.id, model]));
const missing = FALLBACK_MODEL_IDS.filter((id) => !byId.has(id));
if (missing.length > 0) {
  throw new Error(`Fallback model ids are no longer available: ${missing.join(", ")}`);
}
const models = FALLBACK_MODEL_IDS.map((id) => byId.get(id)!);
const refreshedOn = new Date().toISOString().slice(0, 10);
const output = `import type { ZenMuxModel } from "./zenmux-api.js";\n\n` +
  `export const FALLBACK_SOURCE_URL = ${JSON.stringify(MODELS_URL)};\n` +
  `export const FALLBACK_REFRESHED_ON = ${JSON.stringify(refreshedOn)};\n\n` +
  `// Generated by npm run catalog:refresh from the validated live catalog.\n` +
  `export const FALLBACK_MODELS: ZenMuxModel[] = ${JSON.stringify(models, null, 2)};\n`;

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
await writeFile(resolve(root, "src", "fallback-models.ts"), output, "utf8");
console.log(`Wrote ${models.length} fallback models refreshed on ${refreshedOn}`);
