import type { ZenMuxModel } from "./zenmux-api.js";

export const FALLBACK_SOURCE_URL = "https://zenmux.ai/api/v1/models";
export const FALLBACK_REFRESHED_ON = "2026-07-18";

// Generated by npm run catalog:refresh from the validated live catalog.
export const FALLBACK_MODELS: ZenMuxModel[] = [
  {
    "id": "moonshotai/kimi-k3-free",
    "display_name": "MoonshotAI: Kimi K3 (Free)",
    "context_length": 1048576,
    "context_size": 1048576,
    "capabilities": {
      "reasoning": true,
      "function_calling": false,
      "structured_outputs": false
    },
    "input_modalities": [
      "text",
      "image"
    ],
    "output_modalities": [
      "text"
    ],
    "pricings": {
      "prompt": {
        "value": 0,
        "unit": "perMTokens"
      },
      "completion": {
        "value": 0,
        "unit": "perMTokens"
      },
      "input_cache_read": {
        "value": 0,
        "unit": "perMTokens"
      }
    },
    "pricing": {
      "prompt": {
        "value": 0,
        "unit": "perMTokens"
      },
      "completion": {
        "value": 0,
        "unit": "perMTokens"
      },
      "input_cache_read": {
        "value": 0,
        "unit": "perMTokens"
      }
    }
  },
  {
    "id": "moonshotai/kimi-k3",
    "display_name": "MoonshotAI: Kimi K3",
    "context_length": 1048576,
    "context_size": 1048576,
    "capabilities": {
      "reasoning": true,
      "function_calling": false,
      "structured_outputs": false
    },
    "input_modalities": [
      "text",
      "image"
    ],
    "output_modalities": [
      "text"
    ],
    "pricings": {
      "prompt": {
        "value": 3,
        "unit": "perMTokens"
      },
      "completion": {
        "value": 15,
        "unit": "perMTokens"
      },
      "input_cache_read": {
        "value": 0.3,
        "unit": "perMTokens"
      }
    },
    "pricing": {
      "prompt": {
        "value": 3,
        "unit": "perMTokens"
      },
      "completion": {
        "value": 15,
        "unit": "perMTokens"
      },
      "input_cache_read": {
        "value": 0.3,
        "unit": "perMTokens"
      }
    }
  },
  {
    "id": "openai/gpt-5.6-luna",
    "display_name": "OpenAI: GPT-5.6 Luna",
    "context_length": 1050000,
    "context_size": 1050000,
    "capabilities": {
      "reasoning": true,
      "function_calling": false,
      "structured_outputs": false
    },
    "input_modalities": [
      "text",
      "image"
    ],
    "output_modalities": [
      "text"
    ],
    "pricings": {
      "prompt": {
        "value": 1,
        "unit": "perMTokens",
        "conditions": {
          "prompt_tokens": {
            "unit": "kTokens",
            "gte": 0,
            "lt": 272
          }
        }
      },
      "completion": {
        "value": 6,
        "unit": "perMTokens",
        "conditions": {
          "prompt_tokens": {
            "unit": "kTokens",
            "gte": 0,
            "lt": 272
          }
        }
      },
      "input_cache_read": {
        "value": 0.1,
        "unit": "perMTokens",
        "conditions": {
          "prompt_tokens": {
            "unit": "kTokens",
            "gte": 0,
            "lt": 272
          }
        }
      },
      "input_cache_write": {
        "value": 1.25,
        "unit": "perMTokens",
        "conditions": {
          "prompt_tokens": {
            "unit": "kTokens",
            "gte": 0,
            "lt": 272
          }
        }
      }
    },
    "pricing": {
      "prompt": {
        "value": 1,
        "unit": "perMTokens",
        "conditions": {
          "prompt_tokens": {
            "unit": "kTokens",
            "gte": 0,
            "lt": 272
          }
        }
      },
      "completion": {
        "value": 6,
        "unit": "perMTokens",
        "conditions": {
          "prompt_tokens": {
            "unit": "kTokens",
            "gte": 0,
            "lt": 272
          }
        }
      },
      "input_cache_read": {
        "value": 0.1,
        "unit": "perMTokens",
        "conditions": {
          "prompt_tokens": {
            "unit": "kTokens",
            "gte": 0,
            "lt": 272
          }
        }
      },
      "input_cache_write": {
        "value": 1.25,
        "unit": "perMTokens",
        "conditions": {
          "prompt_tokens": {
            "unit": "kTokens",
            "gte": 0,
            "lt": 272
          }
        }
      }
    }
  },
  {
    "id": "openai/gpt-5.6-terra",
    "display_name": "OpenAI: GPT-5.6 Terra",
    "context_length": 1050000,
    "context_size": 1050000,
    "capabilities": {
      "reasoning": true,
      "function_calling": false,
      "structured_outputs": false
    },
    "input_modalities": [
      "text",
      "image"
    ],
    "output_modalities": [
      "text"
    ],
    "pricings": {
      "prompt": {
        "value": 2.5,
        "unit": "perMTokens",
        "conditions": {
          "prompt_tokens": {
            "unit": "kTokens",
            "gte": 0,
            "lte": 272
          }
        }
      },
      "completion": {
        "value": 15,
        "unit": "perMTokens",
        "conditions": {
          "prompt_tokens": {
            "unit": "kTokens",
            "gte": 0,
            "lte": 272
          }
        }
      },
      "input_cache_read": {
        "value": 0.25,
        "unit": "perMTokens",
        "conditions": {
          "prompt_tokens": {
            "unit": "kTokens",
            "gte": 0,
            "lte": 272
          }
        }
      },
      "input_cache_write": {
        "value": 3.125,
        "unit": "perMTokens",
        "conditions": {
          "prompt_tokens": {
            "unit": "kTokens",
            "gte": 0,
            "lte": 272
          }
        }
      }
    },
    "pricing": {
      "prompt": {
        "value": 2.5,
        "unit": "perMTokens",
        "conditions": {
          "prompt_tokens": {
            "unit": "kTokens",
            "gte": 0,
            "lte": 272
          }
        }
      },
      "completion": {
        "value": 15,
        "unit": "perMTokens",
        "conditions": {
          "prompt_tokens": {
            "unit": "kTokens",
            "gte": 0,
            "lte": 272
          }
        }
      },
      "input_cache_read": {
        "value": 0.25,
        "unit": "perMTokens",
        "conditions": {
          "prompt_tokens": {
            "unit": "kTokens",
            "gte": 0,
            "lte": 272
          }
        }
      },
      "input_cache_write": {
        "value": 3.125,
        "unit": "perMTokens",
        "conditions": {
          "prompt_tokens": {
            "unit": "kTokens",
            "gte": 0,
            "lte": 272
          }
        }
      }
    }
  },
  {
    "id": "x-ai/grok-4.5",
    "display_name": "xAI: Grok 4.5",
    "context_length": 500000,
    "context_size": 500000,
    "capabilities": {
      "reasoning": true,
      "function_calling": false,
      "structured_outputs": false
    },
    "input_modalities": [
      "text",
      "image"
    ],
    "output_modalities": [
      "text"
    ],
    "pricings": {
      "prompt": {
        "value": 2,
        "unit": "perMTokens",
        "conditions": {
          "prompt_tokens": {
            "unit": "kTokens",
            "gte": 0,
            "lte": 200
          }
        }
      },
      "completion": {
        "value": 6,
        "unit": "perMTokens",
        "conditions": {
          "prompt_tokens": {
            "unit": "kTokens",
            "gte": 0,
            "lte": 200
          }
        }
      },
      "input_cache_read": {
        "value": 0.5,
        "unit": "perMTokens",
        "conditions": {
          "prompt_tokens": {
            "unit": "kTokens",
            "gte": 0,
            "lte": 200
          }
        }
      }
    },
    "pricing": {
      "prompt": {
        "value": 2,
        "unit": "perMTokens",
        "conditions": {
          "prompt_tokens": {
            "unit": "kTokens",
            "gte": 0,
            "lte": 200
          }
        }
      },
      "completion": {
        "value": 6,
        "unit": "perMTokens",
        "conditions": {
          "prompt_tokens": {
            "unit": "kTokens",
            "gte": 0,
            "lte": 200
          }
        }
      },
      "input_cache_read": {
        "value": 0.5,
        "unit": "perMTokens",
        "conditions": {
          "prompt_tokens": {
            "unit": "kTokens",
            "gte": 0,
            "lte": 200
          }
        }
      }
    }
  },
  {
    "id": "anthropic/claude-sonnet-5",
    "display_name": "Anthropic: Claude Sonnet 5",
    "context_length": 1000000,
    "context_size": 1000000,
    "capabilities": {
      "reasoning": true,
      "function_calling": false,
      "structured_outputs": false
    },
    "input_modalities": [
      "image",
      "text"
    ],
    "output_modalities": [
      "text"
    ],
    "pricings": {
      "prompt": {
        "value": 2,
        "unit": "perMTokens"
      },
      "completion": {
        "value": 10,
        "unit": "perMTokens"
      },
      "input_cache_read": {
        "value": 0.2,
        "unit": "perMTokens"
      }
    },
    "pricing": {
      "prompt": {
        "value": 2,
        "unit": "perMTokens"
      },
      "completion": {
        "value": 10,
        "unit": "perMTokens"
      },
      "input_cache_read": {
        "value": 0.2,
        "unit": "perMTokens"
      }
    }
  },
  {
    "id": "z-ai/glm-5.2",
    "display_name": "Z.AI: GLM 5.2",
    "context_length": 1000000,
    "context_size": 1000000,
    "capabilities": {
      "reasoning": true,
      "function_calling": false,
      "structured_outputs": false
    },
    "input_modalities": [
      "text"
    ],
    "output_modalities": [
      "text"
    ],
    "pricings": {
      "prompt": {
        "value": 0.98,
        "unit": "perMTokens"
      },
      "completion": {
        "value": 3.08,
        "unit": "perMTokens"
      },
      "input_cache_read": {
        "value": 0.182,
        "unit": "perMTokens"
      }
    },
    "pricing": {
      "prompt": {
        "value": 0.98,
        "unit": "perMTokens"
      },
      "completion": {
        "value": 3.08,
        "unit": "perMTokens"
      },
      "input_cache_read": {
        "value": 0.182,
        "unit": "perMTokens"
      }
    }
  },
  {
    "id": "moonshotai/kimi-k2.7-code",
    "display_name": "MoonshotAI: Kimi K2.7 Code",
    "context_length": 262144,
    "context_size": 262144,
    "capabilities": {
      "reasoning": true,
      "function_calling": false,
      "structured_outputs": false
    },
    "input_modalities": [
      "text",
      "image",
      "video"
    ],
    "output_modalities": [
      "text"
    ],
    "pricings": {
      "prompt": {
        "value": 0.4257729,
        "unit": "perMTokens"
      },
      "completion": {
        "value": 1.792728,
        "unit": "perMTokens"
      },
      "input_cache_read": {
        "value": 0.08515458,
        "unit": "perMTokens"
      }
    },
    "pricing": {
      "prompt": {
        "value": 0.4257729,
        "unit": "perMTokens"
      },
      "completion": {
        "value": 1.792728,
        "unit": "perMTokens"
      },
      "input_cache_read": {
        "value": 0.08515458,
        "unit": "perMTokens"
      }
    }
  },
  {
    "id": "qwen/qwen3.7-plus",
    "display_name": "Qwen: Qwen3.7-Plus",
    "context_length": 1000000,
    "context_size": 1000000,
    "capabilities": {
      "reasoning": true,
      "function_calling": false,
      "structured_outputs": false
    },
    "input_modalities": [
      "text",
      "image",
      "video"
    ],
    "output_modalities": [
      "text"
    ],
    "pricings": {
      "prompt": {
        "value": 0.1373076,
        "unit": "perMTokens",
        "conditions": {
          "prompt_tokens": {
            "unit": "kTokens",
            "gte": 0,
            "lte": 256
          }
        }
      },
      "completion": {
        "value": 0.5492304,
        "unit": "perMTokens",
        "conditions": {
          "prompt_tokens": {
            "unit": "kTokens",
            "gte": 0,
            "lte": 256
          }
        }
      },
      "input_cache_read": {
        "value": 0.01373076,
        "unit": "perMTokens",
        "conditions": {
          "prompt_tokens": {
            "unit": "kTokens",
            "gte": 0,
            "lte": 256
          }
        }
      },
      "input_cache_write": {
        "value": 0.1716345,
        "unit": "perMTokens",
        "conditions": {
          "prompt_tokens": {
            "unit": "kTokens",
            "gte": 0,
            "lte": 256
          }
        }
      }
    },
    "pricing": {
      "prompt": {
        "value": 0.1373076,
        "unit": "perMTokens",
        "conditions": {
          "prompt_tokens": {
            "unit": "kTokens",
            "gte": 0,
            "lte": 256
          }
        }
      },
      "completion": {
        "value": 0.5492304,
        "unit": "perMTokens",
        "conditions": {
          "prompt_tokens": {
            "unit": "kTokens",
            "gte": 0,
            "lte": 256
          }
        }
      },
      "input_cache_read": {
        "value": 0.01373076,
        "unit": "perMTokens",
        "conditions": {
          "prompt_tokens": {
            "unit": "kTokens",
            "gte": 0,
            "lte": 256
          }
        }
      },
      "input_cache_write": {
        "value": 0.1716345,
        "unit": "perMTokens",
        "conditions": {
          "prompt_tokens": {
            "unit": "kTokens",
            "gte": 0,
            "lte": 256
          }
        }
      }
    }
  },
  {
    "id": "google/gemini-3.1-pro-preview",
    "display_name": "Google: Gemini 3.1 Pro Preview",
    "context_length": 1048576,
    "context_size": 1048576,
    "capabilities": {
      "reasoning": true,
      "function_calling": false,
      "structured_outputs": false
    },
    "input_modalities": [
      "text",
      "image",
      "audio",
      "video"
    ],
    "output_modalities": [
      "text"
    ],
    "pricings": {
      "prompt": {
        "value": 2,
        "unit": "perMTokens",
        "conditions": {
          "prompt_tokens": {
            "unit": "kTokens",
            "gte": 0,
            "lte": 200
          }
        }
      },
      "completion": {
        "value": 12,
        "unit": "perMTokens",
        "conditions": {
          "prompt_tokens": {
            "unit": "kTokens",
            "gte": 0,
            "lte": 200
          }
        }
      },
      "input_cache_read": {
        "value": 0.2,
        "unit": "perMTokens",
        "conditions": {
          "prompt_tokens": {
            "unit": "kTokens",
            "gte": 0,
            "lte": 200
          }
        }
      }
    },
    "pricing": {
      "prompt": {
        "value": 2,
        "unit": "perMTokens",
        "conditions": {
          "prompt_tokens": {
            "unit": "kTokens",
            "gte": 0,
            "lte": 200
          }
        }
      },
      "completion": {
        "value": 12,
        "unit": "perMTokens",
        "conditions": {
          "prompt_tokens": {
            "unit": "kTokens",
            "gte": 0,
            "lte": 200
          }
        }
      },
      "input_cache_read": {
        "value": 0.2,
        "unit": "perMTokens",
        "conditions": {
          "prompt_tokens": {
            "unit": "kTokens",
            "gte": 0,
            "lte": 200
          }
        }
      }
    }
  },
  {
    "id": "deepseek/deepseek-v4-pro",
    "display_name": "DeepSeek: DeepSeek V4 Pro",
    "context_length": 1000000,
    "context_size": 1000000,
    "capabilities": {
      "reasoning": true,
      "function_calling": false,
      "structured_outputs": false
    },
    "input_modalities": [
      "text"
    ],
    "output_modalities": [
      "text"
    ],
    "pricings": {
      "prompt": {
        "value": 0.435,
        "unit": "perMTokens"
      },
      "completion": {
        "value": 0.87,
        "unit": "perMTokens"
      },
      "input_cache_read": {
        "value": 0.003625,
        "unit": "perMTokens"
      }
    },
    "pricing": {
      "prompt": {
        "value": 0.435,
        "unit": "perMTokens"
      },
      "completion": {
        "value": 0.87,
        "unit": "perMTokens"
      },
      "input_cache_read": {
        "value": 0.003625,
        "unit": "perMTokens"
      }
    }
  },
  {
    "id": "minimax/minimax-m3",
    "display_name": "MiniMax: MiniMax M3",
    "context_length": 1000000,
    "context_size": 1000000,
    "capabilities": {
      "reasoning": true,
      "function_calling": false,
      "structured_outputs": false
    },
    "input_modalities": [
      "text",
      "image",
      "video"
    ],
    "output_modalities": [
      "text"
    ],
    "pricings": {
      "prompt": {
        "value": 0.1373076,
        "unit": "perMTokens",
        "conditions": {
          "prompt_tokens": {
            "unit": "kTokens",
            "gte": 0,
            "lt": 512
          }
        }
      },
      "completion": {
        "value": 0.5492304,
        "unit": "perMTokens",
        "conditions": {
          "prompt_tokens": {
            "unit": "kTokens",
            "gte": 0,
            "lt": 512
          }
        }
      },
      "input_cache_read": {
        "value": 0.02746152,
        "unit": "perMTokens",
        "conditions": {
          "prompt_tokens": {
            "unit": "kTokens",
            "gte": 0,
            "lt": 512
          }
        }
      }
    },
    "pricing": {
      "prompt": {
        "value": 0.1373076,
        "unit": "perMTokens",
        "conditions": {
          "prompt_tokens": {
            "unit": "kTokens",
            "gte": 0,
            "lt": 512
          }
        }
      },
      "completion": {
        "value": 0.5492304,
        "unit": "perMTokens",
        "conditions": {
          "prompt_tokens": {
            "unit": "kTokens",
            "gte": 0,
            "lt": 512
          }
        }
      },
      "input_cache_read": {
        "value": 0.02746152,
        "unit": "perMTokens",
        "conditions": {
          "prompt_tokens": {
            "unit": "kTokens",
            "gte": 0,
            "lt": 512
          }
        }
      }
    }
  }
];
